### ISSUE TITLE
Input Forms

### ISSUE THREAD

**Issue by Deusdictum** [heardrwt/BringBackDelete#1]
Whenever you type something in the input forms on a website and want to delete a character, BringBackDelete is still being activated. So, instead of deleting text, you are sent back to the previous page (which on many sites results in losing all the text you've typed).

**Comment by chr4004** [comment]
Works for me, don't have this problem.

**Comment by heardrwt** [comment]
I dont see this issue either. Can you let us know what version of Safari / OS X you are seeing it under. 
Thanks.

**Comment by Deusdictum** [comment]
After I have restarted my computer, the problem was gone.
I'm using Safari 6.0 (7536.25) and OS X Lion 10.7.4.

**Comment by heardrwt** [comment]
Hmm, weird. Closing out. Re-open if you can repro.
